#!/bin/bash
# Configure Dolphin to my Taste


# General Settings

###############################################################
Settings > Configure Dolphin > Startup

x
x
_/
x


###############################################################
Settings > Configure Dolphin > View Modes

Icons : 
Default = 96 Pixels
Preview = 256 Pixels (Biggest)

Font = Sans Serif - Normal - 22
Width = Huge
Maximum lines = Unlimited

###############################################################
Settings > Configure Dolphin > Nabigation

(*)
( )

_/
x


###############################################################
Settings > Configure Dolphin > Services

_/ Copy to and Move to
_/ Compress*
_/ Extract*
_/ Delete
_/ Open Terminal here

###############################################################
Settings > Configure Dolphin > Trash

x
_/

Maximum size = 10%



###############################################################
Settings > Configure Dolphin > General

Behaviour:
(*)
( )

_/
_/
_/
_/


Previews:
_/ Folders
_/ Images
_/ Jpegs
_/ Text files
_/ Video files (ffmpeg)


Confirmations:
x
_/

_/


Status Bar:
x
_/







# Toolbars 

###############################################################
Settings > Configure Toolbars

Toolbar :=

Back
Forward
Up
Reload
seperator
Select all
Rename
Find
Preview
Split
Show Hidden
Show in Groups
seperator
Icons
Compact
Details
Sort By







# General View of folders
###############################################################
View > Adjust view properties

Icons:

Sorting : Ascending | Name

_/
x
x
x

Additional Information:

Name
Size
Type
Link Destination
Permissions
Owner



Apply to:
All folders



_/     # Use as default view properties



###############################################################

