#!/bin/bash
# Change mouse size in xfce4

  p xcursor-themes
  
  echo "Xcursor.size: 44" > ~/.Xdefaults
  
  # Reboot
  
  # Go to settings in XFCE4 > Mouse & Touchpad > Themes > Change Themes & Size 
  # Cycle Compiz - Xfwm - Kwin- Metacity
  # untill it clicks :)
  
  
