#!/bin/bash
# Configure Redshift


# Install
	p redshift	

# start redshift

	redshift 
 #or
	gtk-redshift

# Start redshift with forced region (if failed to get location automatically)
gtk-redshift -l 24.38:46.46
