#!/bin/bash


# To make subtitle font look normal in SMPlayer


  sudo nano /home/abz/.mplayer/config

  # Add this line

subfont-osd-scale=2


  
# To make seek always accurate

  # Add this in the <Options for mplayer2> Option in SMPlayer

--hr-seek=always
  
 
