#!/bin/bash
# How to cut sections from a video

 # cut from sec 40 to min 1.32
  
    ffmpeg -i Input.ext -vcodec copy -acodec copy -ss 00:00:40 -t 00:01:32 OutPut.ext

------------------------------------------------------------ 
 # to cut multi audio track files
 
    ffmpeg -i Input.ext -vcodec copy -c:a copy -map 0:1 -map 0:2 -acodec copy -ss 00:00:40 -t 00:01:32 OutPut.ext
 
------------------------------------------------------------ 
 # to only cut audio (difference is "-vcodec copy")

    ffmpeg -i Input.ext -acodec copy -ss 00:00:40 -t 00:01:32 OutPut.ext
