#!/bin/bash

# These are all the configs relating to a good XBMC installation


# import watched state


  n .xbmc/userdata/advancedsettings.xml

# Put inside  

    <advancedsettings>
	<videolibrary>
	      <importwatchedstate>true</importwatchedstate>
	</videolibrary>
    </advancedsettings>

  
  
# External Players
  
  
  n playercorefactory.xml
  
# Put inside  

 <playercorefactory>
 <players>
   <player name="Smplayer" type="ExternalPlayer" audio="false" video="true">
     <filename>/usr/bin/smplayer</filename>
     <args>"{1}"</args>
     <hidexbmc>false</hidexbmc>
     <hideconsole>false</hideconsole>
     <warpcursor>none</warpcursor>
   </player>
   <player name="Vlc" type="ExternalPlayer" audio="false" video="true">
     <filename>/usr/bin/vlc</filename>
     <args>"{1}"</args>
     <hidexbmc>false</hidexbmc>
     <hideconsole>false</hideconsole>
     <warpcursor>none</warpcursor>
   </player>
 </players>
 <rules action="prepend">
   <rule video="true" player="Smplayer"/>
   <rule video="true" player="Vlc"/>
   <rule audio="true" player="dvdplayer"/>
 </rules>
</playercorefactory>


####### View corruption #######


	# if files dont show up in Library mode.

	n .xbmc/userdata/guisettings.xml 
	
	# Change the 0 to 1
        <myvideos>
        <watchmodemovies>0</watchmodemovies>
        <watchmodetvshows>0</watchmodetvshows>
