#!/bin/bash
# find the extension of the file & either cut it or only show it


# Show only the file name

  echo "file.avi" | rev | cut -d"." -f2- | rev
	
    
# Show filename and/or parts of the path
  echo "/media/NAS/file.avi" | rev | cut -d"." -f2- | cut -d/ -f2- | rev 
	
	#explanation 
	#  rev "		 	to reverse the path
	#  cut -d. 		to remove the extension
	#  cut -d/ 		to select paths by the slash
  
# Show only the extension

 #method 1
  echo "file.avi" | sed 's/^.*\.\([^.]*\)$/\1/'
 
 #method 2 (better)
  echo "file.avi" | rev | cut -d"." -f1 | rev




