#!/bin/bash
# Prevent access to unmounted directory

  
  # When Local dir & unmounted, do:
  
  sudo chattr +i /media/unmounted-dir

  # When Remote dir (e.g: NFS) & unmounted:

    you are "fucked"
