#!/bin/bash




# Passwordless ssh logins

# on the host

  ssh-keygen -t rsa


  ssh-copy-id <ip-of-client>
  
  
----------------------------------

# Disabling password logins and using only the public key

# on the host
n /etc/ssh/sshd_config

	PasswordAuthentication no
	ChallengeResponseAuthentication no
	
#Copying the public key to the remote server

#	Simple method

	# HINT: Do the ssh-copy-id from all computers while password logins
	#+ are allowed, then disable password logins and only allow Keys


	# If your key file is ~/.ssh/id_rsa.pub you can simply enter:

	ssh-copy-id remote-server.org

	#If username differs on remote machine, prepend the username@server

	ssh-copy-id username@remote-server.org

	#If your public key filename is anything other than the default of ~/.ssh/id_rsa.pub you will get an error stating /usr/bin/ssh-copy-id: ERROR: No identities found. In this case, you must explicitly provide the location of the public key.

	ssh-copy-id -i ~/.ssh/id_rsa.pub username@remote-server.org

	#If the ssh server is listening on a port other than default of 22, be sure to include it within the host argument.

	ssh-copy-id -i ~/.ssh/id_rsa.pub -p 221 username@remote-server.org



#Traditional method

	#By default, for OpenSSH, the public key needs to be concatenated with ~/.ssh/authorized_keys. Begin by copying the public key to the remote server.

	scp ~/.ssh/id_rsa.pub username@remote-server.org:

	#The above example copies the public key (id_rsa.pub) to your home directory on the remote server via scp. Do not forget to include the : at the end of the server address. Also note that the name of your public key may differ from the example given.

	#On the remote server, you will need to  append your public key to the authorized_keys file. 
