#!/bin/bash

  # Install
  sudo pacman -Ss iproute2

# Adding a VLAN
{

  #To add a VLAN use a command with this needlessly long syntax:

   ip link add link INTERFACE name INTERFACE.VID type vlan id VID 

  #Example:

   ip link add link eth0 name eth0.100 type vlan id 100 

}

# Configuring the VLAN
{
  #To add an IPv4 address the the just created vlan link, and activate the link you can do:

  ip addr add IP/NETMASK brd BROADCAST-ADDR dev INTERFACE.VID
  ip link set dev INTERFACE.VID up

  #Example:

  ip addr add 192.168.100.1/24 brd 192.168.100.255 dev eth0.100
  ip link set dev eth0.100 up

}

# Removing a VLAN
{

  ip link delete INTERFACE.VID

  # Example:

  ip link delete eth0.100

}



#######################################################################
	
# Resources

https://wiki.archlinux.org/index.php/VLAN
