#!/bin/bash
# Install Archlinux from the newtork


# Step 1: 
Download the latest Arch ISO

# Step 2:
# Server setup

# Mount the ISO:
sudo mkdir -p /mnt/archiso
sudo mount -o loop,ro /path/to/arch.iso /mnt/archiso

# Install the DHCP-TFTP , HTTP & NBD server
 p dnsmasq darkhttpd nbd


# Know your ethernet name
ip link show


# Configure dnsmasq
sudo nano /etc/dnsmasq.conf

port=0
# change me = (ethernet name)
interface=enp2s0
bind-interfaces
# change me =  (ip address)
dhcp-range=10.0.0.120,10.0.0.121,12h
dhcp-boot=/arch/boot/syslinux/lpxelinux.0
dhcp-option-force=209,boot/syslinux/archiso.cfg
dhcp-option-force=210,/arch/
enable-tftp
tftp-root=/mnt/archiso

# Start the DHCP-TFTP server
sudo systemctl start dnsmasq.service


# Methods Available to install


# Method 1 : (HTTP) [very easy]

	# Start the HTTP server
	sudo darkhttpd /mnt/archiso



# Method 2 : (NBD) [easy]

	sudo nano /etc/nbd-server/config

# Add to the end of the file
[generic]
[archiso]
    readonly = true
    exportname = /path/to/arch.iso
    
    # Start the NBD server
	sudo systemctl start nbd.service




# Method 3 : (NFS) [hard'ish]

	sudo mkdir -p /run/archiso/bootmnt
	
	sudo mount -R /mnt/archiso /run/archiso/bootmnt
	
	sudo nano /etc/exports

# add to the end of the file
/run/archiso/bootmnt 10.0.0.0/24(ro,no_subtree_check)


	sudo exportfs -r -a -v



# Reboot the client & choose PXE boot
# Now use the Arch Install Guide to start your awesome installation
