#!/bin/bash
# How to install grub2 on Arch

 p grub-bios
 p os-prober

 sudo grub-install /dev/sdX

 sudo grub-mkconfig -o /boot/grub/grub.cfg



# The file to edit is

 sudo nano /etc/default/grub
 
 
 
 
 
# To change the resolution used on graphical terminal
GRUB_GFXMODE=640x480x32


# Fix broken grub.cfg gen (add to /etc/default/grub)
GRUB_DISABLE_SUBMENU=y


---------------------------------------------------------------------- 
# To add a custom entry



# edit 

 sudo nano /etc/grub.d/40_custom  

 #(set root=(hd0,6) = "The boot folder" which means sda6 is the /boot 
 # and root=UUIDXXXX = "The root folder" which means sda5 is /root)


menuentry "Arch Backup" {
set root=(hd0,6)
linux /vmlinuz-linux root=UUID=19765ba3-8ae9-4b92-b12c-ff1bea99cedc
initrd /initramfs-linux.img
}



# generate the config again

sudo grub-mkconfig -o /boot/grub/grub.cfg




#######################################################################
	
# Resources
 
https://wiki.archlinux.org/index.php/GRUB2
