#!/bin/bash
# When 4G slows to a crawl; do this:

 
send 4469 to 902
to cancel 4G

# then

send 4466 to 902
to enable 4G again 

# Restart the modem when 4G is back on

############

 ارسل 4469 الى 902
لإلغاء الجيل الرابع

بعدين ارسل 4466 الى 902
لتفعيل الجيل الرابع وسوي رستارت وتنحل المشكلة
